Update update-environment.yml

diff --git a/.github/workflows/update-environment.yml b/.github/workflows/update-environment.yml
--- a/.github/workflows/update-environment.yml
+++ b/.github/workflows/update-environment.yml
@@ -20,15 +20,46 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: otimizando - criando arquivo sem checkout
+        run: |
+          # Nome do arquivo
+          FILE="package.json"
+          
+          # Verifica se o arquivo já existe
+          if [ ! -f "$FILE" ]; then
+          cat <<EOL > "$FILE"
+          {
+            "dependencies": {
+              "@octokit/rest": "^21.0.0",    
+              "libsodium-wrappers": "^0.7.13"
+            },
+            "name": "app",
+            "version": "1.0.0",
+            "main": "index.js",
+            "devDependencies": {},
+            "scripts": {
+              "test": "echo \\"Error: no test specified\\" && exit 1"
+            },
+            "keywords": [],
+            "author": "",
+            "license": "ISC",
+            "description": ""
+          }
+          EOL
+              echo "$FILE criado com sucesso."
+          else
+              echo "$FILE já existe."
+          fi
+
       - name: Set up Node.js
         uses: actions/setup-node@v4
         with:
           node-version: '22'
           cache: npm
 
-      - name: Install dependencies
-        run: |
-          npm install @octokit/rest@21.0.0 libsodium-wrappers@0.7.13
+      # - name: Install dependencies
+      #   run: |
+      #     npm install @octokit/rest@21.0.0 libsodium-wrappers@0.7.13
 
       - name: atualizando environments
         uses: actions/github-script@v7
